remote_theme: wet-boew/gcweb-jekyll
title: Sample website with GCWeb Jekyll theme

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default
